library(tidyverse)
borderS <- rep('BORDER', 2)
borderN <- rep('BORDER', 3)
fill <- rep('FILL', 5)
origRange <- c(borderS, 1:25, borderN)
combinedIndex <- tibble(modifiedRow = rep(1:28, each = 30), 
                        modifiedRange = rep(1:30, times = 28),
                        originalRow = c(rep(21:15, each = 30), rep(NA, times = 3*30), 
                                        rep(14:8, each = 30), rep(NA, times = 2*30), 
                                        rep(7:1, each = 30), rep(NA, times = 2*30)),
                        originalRange = c(rep(origRange, times = 7), 
                                          rep('BORDER', times = 3*30), 
                                          rep(origRange, times = 7),
                                          rep('BORDER', times = 2*30),
                                          rep(origRange, times = 7), 
                                          rep('BORDER', times = 2*30)),
                        plannedPlotNumber = c(borderS, 1491:1510, fill, borderN,
                                              borderS, 1466:1490, borderN,
                                              borderS, 1441:1465, borderN,
                                              borderS, 1416:1440, borderN,
                                              borderS, 1391:1415, borderN,
                                              borderS, 1366:1390, borderN, 
                                              borderS, 1341:1365, borderN, 
                                              rep('BORDER', 3*30),
                                              borderS, 1321:1340, fill, borderN,
                                              borderS, 1296:1320, borderN, 
                                              borderS, 1271:1295, borderN,
                                              borderS, 1246:1270, borderN,
                                              borderS, 1221:1245, borderN,
                                              borderS, 1196:1220, borderN,
                                              borderS, 1171:1195, borderN,
                                              rep('BORDER', 2*30),
                                              borderS, 1151:1170, fill, borderN, 
                                              borderS, 1126:1150, borderN,
                                              borderS, 1101:1125, borderN,
                                              borderS, 1076:1100, borderN, 
                                              borderS, 1051:1075, borderN,
                                              borderS, 1026:1050, borderN, 
                                              borderS, 1001:1025, borderN, 
                                              rep('BORDER', 2*30)),
                        plantedPlotNumber = c(borderS, 1001:1025, borderN, 
                                              borderS, 1026:1050, borderN,
                                              borderS, 1051:1075, borderN,
                                              borderS, 1076:1100, borderN,
                                              borderS, 1101:1125, borderN, 
                                              borderS, 1126:1150, borderN,
                                              borderS, 1151:1170, fill, borderN,
                                              rep('BORDER', 3*30),
                                              borderS, 1171:1195, borderN, 
                                              borderS, 1196:1220, borderN, 
                                              borderS, 1221:1245, borderN, 
                                              borderS, 1246:1270, borderN, 
                                              borderS, 1271:1295, borderN,
                                              borderS, 1296:1320, borderN,
                                              borderS, 1321:1340, fill, borderN, 
                                              rep('BORDER', 2*30), 
                                              borderS, 1341:1365, borderN,
                                              borderS, 1366:1390, borderN,
                                              borderS, 1391:1415, borderN,
                                              borderS, 1416:1440, borderN,
                                              borderS, 1441:1465, borderN,
                                              borderS, 1466:1490, borderN,
                                              borderS, 1491:1510, fill, borderN, 
                                              rep('BORDER', 2*30)))
